[package]
name = "gtk-extras"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[dependencies]
gtk = { version = "0.7.0", features = ["v3_22"] }
gio = "0.7.0"
shrinkwraprs = "0.2.1"
uuid = "0.7.4"
glib = "0.8.2"
itertools = "0.8.0"
cascade = "0.1.3"
gdk = "0.11.0"
log = "0.4.8"
