[package]
name = "gtk-extras"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[dependencies]
gtk = { version = "0.7", features = ["v3_22"] }
gio = "0.7"
shrinkwraprs = "0.2"
uuid = "0.8"
glib = "0.8"
itertools = "0.8"
cascade = "0.1"
gdk = "0.11"
log = "0.4"
resvg = { version = "0.8", features = ["cairo-backend"] }
